services:
  server:
    container_name: server
    build:
      context: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
    volumes:
      - .:/app

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
